name: Exponential
samples_size: 500
exp_num: 14
distributions:
- type: Exponential
  params:
  - 1.0743044883645778
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.320627219484441
  prior: 1.0
error: false
