name: Exponential
samples_size: 500
exp_num: 99
distributions:
- type: Exponential
  params:
  - 4.858284050306729
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.571023432331397
  prior: 1.0
error: false
