name: Exponential
samples_size: 1000
exp_num: 66
distributions:
- type: Exponential
  params:
  - 3.9023995665766
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.0491203523495067
  prior: 1.0
error: false
