name: Exponential
samples_size: 500
exp_num: 43
distributions:
- type: Exponential
  params:
  - 1.2167015506925798
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.428333225839528
  prior: 1.0
error: false
