name: Exponential
samples_size: 200
exp_num: 78
distributions:
- type: Exponential
  params:
  - 2.3483740776782542
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.885377517772071
  prior: 1.0
error: false
