name: Exponential
samples_size: 500
exp_num: 82
distributions:
- type: Exponential
  params:
  - 1.387433881762383
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.436691063829656
  prior: 1.0
error: false
