name: Exponential
samples_size: 200
exp_num: 64
distributions:
- type: Exponential
  params:
  - 3.454609829850386
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.3025807709843506
  prior: 1.0
error: false
