name: Exponential
samples_size: 500
exp_num: 74
distributions:
- type: Exponential
  params:
  - 1.641921615912542
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.271075595743898
  prior: 1.0
error: false
