name: Exponential
samples_size: 200
exp_num: 29
distributions:
- type: Exponential
  params:
  - 4.252722395102553
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.8842748574582777
  prior: 1.0
error: false
