name: Exponential
samples_size: 200
exp_num: 72
distributions:
- type: Exponential
  params:
  - 4.720257600241767
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.6338097749749828
  prior: 1.0
error: false
