name: Exponential
samples_size: 1000
exp_num: 93
distributions:
- type: Exponential
  params:
  - 3.9811888853785247
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.689200891511809
  prior: 1.0
error: false
