name: Exponential
samples_size: 1000
exp_num: 10
distributions:
- type: Exponential
  params:
  - 0.2460063752465447
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.511499180921559
  prior: 1.0
error: false
