name: Exponential
samples_size: 500
exp_num: 67
distributions:
- type: Exponential
  params:
  - 1.2223355526241115
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.5098757055013895
  prior: 1.0
error: false
