name: Exponential
samples_size: 500
exp_num: 52
distributions:
- type: Exponential
  params:
  - 1.1265844507802898
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.926239856077404
  prior: 1.0
error: false
