name: Exponential
samples_size: 1000
exp_num: 77
distributions:
- type: Exponential
  params:
  - 4.581283189728663
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.527298205182571
  prior: 1.0
error: false
