name: Exponential
samples_size: 1000
exp_num: 3
distributions:
- type: Exponential
  params:
  - 1.4476436600086846
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.0263629026203045
  prior: 1.0
error: false
