name: Exponential
samples_size: 1000
exp_num: 62
distributions:
- type: Exponential
  params:
  - 3.235998823285055
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.780621306387353
  prior: 1.0
error: false
