name: Exponential
samples_size: 500
exp_num: 92
distributions:
- type: Exponential
  params:
  - 3.1744856043451417
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 1.1098595928590522
  prior: 1.0
error: false
