name: Exponential
samples_size: 500
exp_num: 23
distributions:
- type: Exponential
  params:
  - 1.7672275309381604
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.26928873379373
  prior: 1.0
error: false
