name: Exponential
samples_size: 500
exp_num: 60
distributions:
- type: Exponential
  params:
  - 1.9593316646124743
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.525147755495427
  prior: 1.0
error: false
