name: Exponential
samples_size: 500
exp_num: 85
distributions:
- type: Exponential
  params:
  - 2.057062475187947
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.5407456358450013
  prior: 1.0
error: false
