name: Exponential
samples_size: 500
exp_num: 16
distributions:
- type: Exponential
  params:
  - 2.770213254955762
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.19386982931930413
  prior: 1.0
error: false
