name: Exponential
samples_size: 1000
exp_num: 79
distributions:
- type: Exponential
  params:
  - 1.3979128158404572
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.7091671304223462
  prior: 1.0
error: false
