name: Exponential
samples_size: 1000
exp_num: 84
distributions:
- type: Exponential
  params:
  - 4.499332129652137
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.6146671660876453
  prior: 1.0
error: false
