name: Exponential
samples_size: 500
exp_num: 56
distributions:
- type: Exponential
  params:
  - 3.0847419277682424
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 1.0114391460435168
  prior: 1.0
error: false
