name: Exponential
samples_size: 500
exp_num: 70
distributions:
- type: Exponential
  params:
  - 1.4119302922809436
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.8551121489185367
  prior: 1.0
error: false
