name: Exponential
samples_size: 1000
exp_num: 53
distributions:
- type: Exponential
  params:
  - 1.4081913280406557
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.3454765177838011
  prior: 1.0
error: false
