name: Exponential
samples_size: 1000
exp_num: 61
distributions:
- type: Exponential
  params:
  - 4.948664418119317
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.9177487669141664
  prior: 1.0
error: false
