name: Exponential
samples_size: 500
exp_num: 46
distributions:
- type: Exponential
  params:
  - 1.240675343169048
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.9557420400605188
  prior: 1.0
error: false
