name: Exponential
samples_size: 1000
exp_num: 69
distributions:
- type: Exponential
  params:
  - 1.6457199354895016
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.5225162005440611
  prior: 1.0
error: false
