name: Exponential
samples_size: 1000
exp_num: 27
distributions:
- type: Exponential
  params:
  - 0.5544546325627248
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.610908696719203
  prior: 1.0
error: false
