name: Exponential
samples_size: 500
exp_num: 21
distributions:
- type: Exponential
  params:
  - 4.0485143339807586
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.2269338803759475
  prior: 1.0
error: false
