name: Exponential
samples_size: 500
exp_num: 24
distributions:
- type: Exponential
  params:
  - 0.8618495490777296
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.1190779366366845
  prior: 1.0
error: false
