name: Exponential
samples_size: 1000
exp_num: 9
distributions:
- type: Exponential
  params:
  - 2.1674169164578254
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 1.9894151078687496
  prior: 1.0
error: false
