name: Exponential
samples_size: 500
exp_num: 90
distributions:
- type: Exponential
  params:
  - 0.33087023958119943
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.590584893999282
  prior: 1.0
error: false
