name: Exponential
samples_size: 500
exp_num: 75
distributions:
- type: Exponential
  params:
  - 3.3116494599449124
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.28607267825439564
  prior: 1.0
error: false
