name: Exponential
samples_size: 1000
exp_num: 98
distributions:
- type: Exponential
  params:
  - 2.6926602909857715
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.9729866966802128
  prior: 1.0
error: false
