name: Exponential
samples_size: 200
exp_num: 22
distributions:
- type: Exponential
  params:
  - 3.5208830354423117
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.9633217109949789
  prior: 1.0
error: false
