name: Exponential
samples_size: 500
exp_num: 55
distributions:
- type: Exponential
  params:
  - 3.2753733877083087
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 1.9034554024682393
  prior: 1.0
error: false
