name: Exponential
samples_size: 500
exp_num: 51
distributions:
- type: Exponential
  params:
  - 1.9138867388727252
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.256962589120435
  prior: 1.0
error: false
