name: Exponential
samples_size: 200
exp_num: 17
distributions:
- type: Exponential
  params:
  - 1.180159047999414
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.2187053108620574
  prior: 1.0
error: false
