name: Exponential
samples_size: 1000
exp_num: 71
distributions:
- type: Exponential
  params:
  - 1.1338159335729998
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.056598709574812
  prior: 1.0
error: false
