name: Exponential
samples_size: 200
exp_num: 25
distributions:
- type: Exponential
  params:
  - 4.790344053813228
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 1.9417055998145996
  prior: 1.0
error: false
