name: Exponential
samples_size: 1000
exp_num: 96
distributions:
- type: Exponential
  params:
  - 1.9699345038820304
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.920591294593855
  prior: 1.0
error: false
