name: Exponential
samples_size: 500
exp_num: 44
distributions:
- type: Exponential
  params:
  - 1.5180010216503252
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.5610836709998318
  prior: 1.0
error: false
