name: Exponential
samples_size: 200
exp_num: 89
distributions:
- type: Exponential
  params:
  - 0.5454561196515901
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.30033605811087
  prior: 1.0
error: false
