name: Exponential
samples_size: 200
exp_num: 86
distributions:
- type: Exponential
  params:
  - 1.1746717198706884
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.692986611990383
  prior: 1.0
error: false
