name: Exponential
samples_size: 500
exp_num: 40
distributions:
- type: Exponential
  params:
  - 2.9290255117581343
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.292871221054551
  prior: 1.0
error: false
