name: Exponential
samples_size: 200
exp_num: 4
distributions:
- type: Exponential
  params:
  - 1.1937326169292317
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.6048994790191499
  prior: 1.0
error: false
