name: Exponential
samples_size: 500
exp_num: 26
distributions:
- type: Exponential
  params:
  - 1.7493132710518713
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.5691412559674413
  prior: 1.0
error: false
