name: Exponential
samples_size: 500
exp_num: 87
distributions:
- type: Exponential
  params:
  - 4.98793427182604
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.5447952735092416
  prior: 1.0
error: false
