name: Exponential
samples_size: 500
exp_num: 76
distributions:
- type: Exponential
  params:
  - 2.038596315197255
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.11234538717720373
  prior: 1.0
error: false
