name: Exponential
samples_size: 1000
exp_num: 19
distributions:
- type: Exponential
  params:
  - 4.066209237721351
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.2762143026351795
  prior: 1.0
error: false
