name: Exponential
samples_size: 500
exp_num: 31
distributions:
- type: Exponential
  params:
  - 4.054928539044463
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.9182787335739615
  prior: 1.0
error: false
