name: Exponential
samples_size: 500
exp_num: 38
distributions:
- type: Exponential
  params:
  - 3.130746786584806
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.454886146467329
  prior: 1.0
error: false
