name: Exponential
samples_size: 200
exp_num: 81
distributions:
- type: Exponential
  params:
  - 2.850703857399439
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.528708467829088
  prior: 1.0
error: false
