name: Exponential
samples_size: 1000
exp_num: 7
distributions:
- type: Exponential
  params:
  - 4.471679881753743
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.357537492979165
  prior: 1.0
error: false
