name: Exponential
samples_size: 1000
exp_num: 1
distributions:
- type: Exponential
  params:
  - 3.2331913124436307
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.28890401275316224
  prior: 1.0
error: false
