name: Exponential
samples_size: 200
exp_num: 80
distributions:
- type: Exponential
  params:
  - 1.3084747877005192
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.946996369117584
  prior: 1.0
error: false
