name: Exponential
samples_size: 200
exp_num: 6
distributions:
- type: Exponential
  params:
  - 3.415827488372266
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.6551791530499604
  prior: 1.0
error: false
