name: Exponential
samples_size: 200
exp_num: 13
distributions:
- type: Exponential
  params:
  - 0.23002625145093178
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.9854612311109427
  prior: 1.0
error: false
