name: Exponential
samples_size: 200
exp_num: 28
distributions:
- type: Exponential
  params:
  - 0.5739102464839737
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.5302884700197796
  prior: 1.0
error: false
