name: Exponential
samples_size: 1000
exp_num: 39
distributions:
- type: Exponential
  params:
  - 4.322363811522808
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 2.6590383682791745
  prior: 1.0
error: false
