name: Exponential
samples_size: 1000
exp_num: 57
distributions:
- type: Exponential
  params:
  - 0.9385793761706753
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 3.061953783368472
  prior: 1.0
error: false
