name: Exponential
samples_size: 200
exp_num: 37
distributions:
- type: Exponential
  params:
  - 4.164082854839675
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 1.5511829394762886
  prior: 1.0
error: false
