name: Exponential
samples_size: 500
exp_num: 42
distributions:
- type: Exponential
  params:
  - 0.3245394799127449
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 4.67065757053928
  prior: 1.0
error: false
