name: Exponential
samples_size: 500
exp_num: 34
distributions:
- type: Exponential
  params:
  - 4.868267243498916
  prior: 1.0
init_distributions:
- type: Exponential
  params:
  - 0.39993232424881253
  prior: 1.0
error: false
